acme:
  email_account: ${ACME_EMAIL}

certificates:
  - name: ${DOMAIN}
    domains:
      - ${DOMAIN}
      - "*.${DOMAIN}"
    profile: route53
    deploy_hook: /deploy-hook.sh

profiles:
  - name: route53
    provider: route53
    provider_options:
      aws_access_key_id: ${AWS_ACCESS_KEY_ID}
      aws_secret_access_key: ${AWS_SECRET_ACCESS_KEY}
